### PR TITLE
Put back Snap packaging

### PR DESCRIPTION
**Pull request by vemonet**
PR built on the changes made by https://github.com/tom-james-watson/Emote/pull/99 @tom-james-watson

It put back snap packaging by pulling the changes made by @sonjoonho in https://github.com/tom-james-watson/Emote/pull/96 and fixing the conflicts

core22 was using python 3.10, but with flatpak we use 3.11, so we will need to check if snap still works with 3.11

I don't have snap installed though, so could not try it out, if someone can that would be really nice 😇

### CODE REVIEW

**Comment by tom-james-watson** [comment]
Couple of small fixes: https://github.com/vemonet/Emote/pull/3

**Comment by vemonet** [comment]
I guess we will also want to merge the `flatpak` branch into `master` before sending the PR to flathub

**Comment by tom-james-watson** [comment]
Yeah. I'm still testing the snap side of things. I've reinstalled my OS recently so having to set a few things up for first time again.

**Comment by vemonet** [comment]
Ok, I started a branch to be merged to the flathub repo here: https://github.com/vemonet/flathub/tree/com.tomjwatson.Emote

**Comment by vemonet** [comment]
Thanks, I installed snap and am trying to run the snap install, but it takes forever and does not provide useful feedbacks

I also experimented with setting up a github action to test building the flatpak and snap packages: https://github.com/vemonet/Emote/blob/flatpak/.github/workflows/build.yml
Which might help maintaining the project in the future (and maybe setup a release workflow instead of doing it locally?)

It will try to build it, but I am not sure how to test if the package is properly installed (it success for the 2 currently): https://github.com/vemonet/Emote/actions/runs/5313146037/jobs/9618633302

**Pull request merged**
