### PR TITLE
feat: automatically paste emoji into focussed app

### PR DESCRIPTION
**Pull request by tom-james-watson**
I had had trouble finding a way to get this working whilst the app was
packaged as a snap. Turned out it was as easy as using xdotool and
ensuring that is bundled into the snap file.

Closes https://github.com/tom-james-watson/Emote/issues/13

### CODE REVIEW

**Comment by tom-james-watson** [comment]
CC @lkrms. Emote will now depend on the `xdotool` package. I imagine your build script for arch will need to be updated to list that dependency? It should actually gracefully downgrade to the current functionality if it's not found anyway.

**Comment by lkrms** [comment]
Thanks for the heads up. I'll update it soon.

**Comment by lkrms** [comment]
The AUR package has now been updated to v1.4.0 (assuming `be2939f` is the correct ref).

Related: is there any chance you could please resume tagging releases? Aside from saving packagers like me trawling through commits to guess which one the official snap was built from, GitHub release notifications would kick in, improving the chances of packages being updated promptly :smile: (Plus the repo wouldn't appear to be stuck at v1.0.1 :laughing:)

**Comment by tom-james-watson** [comment]
Great, thanks! 

Ah yeah, good point - I've just pushed v1.4.0 and have made a note to do it for future releases.

**Pull request merged**
