### PR TITLE
Update emojis.csv

### PR DESCRIPTION
**Pull request by reitzig**
- "smiling face with horns" 😈 accessible via `imp`
 - keycaps accessible via English noun, e.g.  4️⃣  via `four`

### CODE REVIEW

**Comment by tom-james-watson** [comment]
Hey, thanks for your PR.

The emojis are actually sourced from https://github.com/hfg-gmuend/openmoji (see https://github.com/tom-james-watson/Emote#attribution), so it's better to actually make these changes upstream, then merge the updated csv into the project. I don't want to maintain an set of changes that need to be carefully merged with the usptream data, so I'm going to have to close this out, sorry!

**Comment by reitzig** [comment]
Ah, I see. ✅

If you don't mind me asking: Why do you keep a copy around instead of pulling it as part of the build process? 🤔

**Comment by tom-james-watson** [comment]
No special reason

**Comment by reitzig** [comment]
Hum. I can't find `imp` or `keycode` in the repo you link. Apparently, these tags (?) don't come from there; from where, though?

**Comment by tom-james-watson** [comment]
I'm not sure what you mean.

You can see the relevant line for where you're adding "imp" here: https://github.com/hfg-gmuend/openmoji/blob/master/data/openmoji.csv#L104. I'm not sure if there's a build process to get that alias there, though.

**Comment by reitzig** [comment]
The commit message says it's an exported file, but I can't find the source. :thinking:

**Comment by reitzig** [comment]
Ah. They seem to be using milesj/emojibase

**Comment by reitzig** [comment]
_They_ [have](https://github.com/milesj/emojibase/blob/master/po/en/shortcodes.po) "smiling imp", though, and I can't tell how it gets lost on its way to emote without much more digging.

image

**Pull request closed without merging**
