### PR TITLE
Add GitHub actions workflow

### PR DESCRIPTION
**Pull request by vemonet**
Added a GitHub actions workflow to test building the package with snap and flatpak

It should already help to catch some errors and test building emote in specific environment

Not sure how we could test if the package was built properly though.

Trying to run the command in the workflow fails: https://github.com/vemonet/Emote/actions/runs/5313394035

* For **flatpak**: https://github.com/vemonet/Emote/actions/runs/5313394035

```
error: app/com.tomjwatson.Emote/x86_64/master not installed
Error: Process completed with exit code 1.
```

* For **snap**:

```
/snap/emote/x1/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas: symbol lookup error: /snap/emote/x1/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas: undefined symbol: g_task_set_static_name
Cannot load module /snap/emote/x1/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: /snap/emote/x1/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
/snap/emote/x1/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so does not export GTK+ IM module API: /snap/emote/x1/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
ERROR: compile_schemas /snap/emote/x1/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas exited abnormally with status 127
ERROR: /snap/emote/x1/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 exited abnormally with status 1

(emote:12085): Gtk-WARNING **: 15:05:34.326: cannot open display: 
Error: Process completed with exit code 1.
```

### CODE REVIEW

**Comment by tom-james-watson** [comment]
FYI I sent an email to the address on your GH profile for if you want to chat more directly

**Comment by tom-james-watson** [comment]
Yeah I think realistically you're not going to be able to run the app in the workflow. I think what would be best would be to just have it create the relevant artifacts for testing purposes.

Then, separately, we can have another workflow that actually publishes the files. That workflow would probably need to recreate the flatpak/snap, which is fine, then just publish them directly.

I'm actually not clear on what the flatpak release flow would actually look like - do you mind explaining how that would work? I understand that flathub themselves would build the package, right? How are new builds kicked off?

**Comment by vemonet** [comment]
I think that to publish a new version of the flatpak package we will just need to change the commit / tag in the manifest YAML in the `flathub/com.tomjwatson.Emote` repository that will be created when our PR is accepted. And we will have the rights to directly commit to this repo, which will trigger building and publishing to flathub?

I think the manifest in the new flathub repo isthis one that actually matters to flathub, the manifest in our repository seems to be mainly there for development

But I am not 100% sure of all this, I am also discovering along with you

**Comment by tom-james-watson** [comment]
OK - that sounds about right to me! Thanks for this!

**Comment by vemonet** [comment]
I just added changes to use the XDG portal Background API instead of asking for filesystem permission as request in https://github.com/flathub/flathub/pull/4265

Would be nice if we could merge asap so that we can try to run another build on flathub

**Comment by tom-james-watson** [comment]
Done - thanks!

**Pull request merged**
