### PR TITLE
Use wtype to paste under wayland

### PR DESCRIPTION
**Pull request by EvyBongers**
Giving it a new try, using [wtype](https://github.com/atx/wtype)

Please let me know what might still be missing to get this merged to master.

### CODE REVIEW

**Comment by tom-james-watson** [comment]
Hello!

When I try to use `wtype` on gnome I get:

```
> wtype ctrl+v
Compositor does not support the virtual keyboard protocol
```

I can't see any info in their docs of which compositors/desktop environments are supported? Is this something that only works on sway (or is it anything that supports wlroots) or something?

**Comment by tom-james-watson** [comment]
Opened an issue here - https://github.com/tom-james-watson/Emote/pull/35.

**Comment by EvyBongers** [comment]
@tom-james-watson I have one question on how to best debug this: when running `wtype` manually (from shell for example), it works perfectly. When I invoke it from Emote, it doesn't paste as expected (but does copy the emoji to the clipboard). I tried adding some `logging.debug()` statements for debugging and had it configured from `main()` to write to a file. The file gets created, but I don't see any lines logged. I'm not sure what's going wrong here and don't know enough about pygobject (or any python that launches a graphical application actually) to properly debug. Could you give me some pointers on how to debug this?

**Comment by tom-james-watson** [comment]
The creator of `wtype` has responded in https://github.com/atx/wtype/issues/22 - it's not going to work in Gnome and I think also not KDE, so this isn't going to be a workable solution, I'm afraid.

**Pull request closed without merging**
