### PR TITLE
Fix skin tone and code point issues, detect static directory location

### PR DESCRIPTION
**Pull request by lkrms**
I'm using the AUR package I maintain and can't easily build and test a snap, but given the encoding errors and code point sequence issues I found in `emojis.csv` and `picker.py` respectively (I felt like I was reliving #24 😆), it may be worth checking whether or not the sequence blocklists in `emojis.py` are necessary when Emote is running as a snap -- if not, #48 may not be as critical.

### Fixes for inconsistent skin tones and blocklisted emoji

Before:
Before

After:
After

`emojis.csv`
- Replace emoji in columns 1 and 12 by evaluating the UTF-16 code points in columns 2 and 13 respectively. **Many contained invalid/unnecessary code points that broke when Emote appended a skin tone code point.**
- Add `update-emojis` shell script to automate this cleanup in future.

`emojis.py`
- Implement "skin tone templates" to accommodate emoji sequences where skin tone code points appear multiple times or must precede other code points. **This was the underlying cause of emoji rendering as two or more separate emoji.**
- Ignore `SKINTONE_SEQUENCE_BLOCKLIST` and `SEQUENCE_BLOCKLIST` except when running as a snap
  - [ ] TODO: test the snap with this PR and reduce or remove these lists if possible?
- Add `get_skintone_template` to add support for skin tone variants in `get_emoji_by_char`. Necessary because stripping skin tone code points doesn't always return a valid "base" emoji.
- Reimplement `strip_char_skintone`.

`picker.py`
- Work around limited support for rendering skin tone modifiers as standalone emoji (e.g. my system displays them as crosshatch boxes) by displaying "waving hand" in the `skintone_combo` dropdown.

### `static/` path fix (when running outside of a snap container)

- Set `config.static_root` based on the detected environment.
- Update references to static assets to use `config.static_root`.

### CODE REVIEW

**Review by tom-james-watson — COMMENTED** [review]
Hi, Luke! Thanks for the PR.

So to be honest I still don't understand what it is that is ostensibly wrong with the old emoji data. But with your changes, some of the emojis revert to old monochrome unicode instead of proper emoji:

## Before

image

image

image

## After

image

image

image

So it doesn't seem like the changes to the emoji data looks right to me to be honest? The data is taken from https://github.com/hfg-gmuend/openmoji/blob/master/data/openmoji.csv. Maybe if you open an issue there for discussion you can get some light shed on your concern?

**Review by tom-james-watson — COMMENTED** [review]
Also without this migration you get a crash if you already have user data:

```diff
diff --git a/emote/user_data.py b/emote/user_data.py
index 08e20a7..39c13ed 100644
--- a/emote/user_data.py
+++ b/emote/user_data.py
@@ -2,7 +2,7 @@ import os
 from pathlib import Path
 import shelve
 
-from emote import emojis
+from emote import emojis, user_data
 
 
 DATA_DIR = os.path.join(Path.home(), ".local/share/Emote")
@@ -124,7 +124,10 @@ def update_theme(theme):
 
 def load_skintone():
     with shelve.open(SHELVE_PATH) as db:
-        return db.get(SKINTONE, DEFAULT_SKINTONE)
+        skintone = db.get(SKINTONE, DEFAULT_SKINTONE)
+        if skintone not in user_data.SKINTONES:
+            skintone = DEFAULT_SKINTONE
+        return skintone
 
 
 def update_skintone(skintone):
```

**Comment by tom-james-watson** [comment]
Closing this out. Release 4.0.0 has just been released, which includes a few changes that affects these parts of the codebase.

Also FYI @lkrms - I don't understand AUR very well, but I think you might need to update the build scripts because some dependencies have changed, for example python 3.11 is now targetted. Thanks!!

**Comment by lkrms** [comment]
> Closing this out. Release 4.0.0 has just been released, which includes a few changes that affects these parts of the codebase.
> 
> Also FYI @lkrms - I don't understand AUR very well, but I think you might need to update the build scripts because some dependencies have changed, for example python 3.11 is now targetted. Thanks!!

Thanks for pinging me, @tom-james-watson. I had been planning to revisit this given all the activity on the project… will try to get an AUR update out in the next couple of days, and if this skin tone issue persists I’ll follow up :)

**Comment by tom-james-watson** [comment]
Perfect, thanks!

**Pull request closed without merging**
