### PR TITLE
Add Native Debian Packaging

### PR DESCRIPTION
**Pull request by 266-750Balloons**
Although the Flatpak packaging does its job very well, I still prefer native package formats when possible. Thus, since about September of last year, I have been intermittently working on the Debian packaging files. I had mostly finished by November and have been using said native package for my own personal use on Debian Trixie since then, with no major issues.

I decided to tidy up my work and make sure it doesn't interfere with other packaging formats. I added Debian detection to the config.py as well as minor handling code in picker.py if it detects it is running as a native Debian package. So far, I have built the Flatpak on Fedora 39 GNOME, which introduces no regressions. Building and installing the Debian packages also works on Ubuntu 23.10 with GNOME.

To build it, you would first go to the repo directory, and install the build dependencies (```sudo apt-get build-essential dh-python python3 debhelper-compat python3-setuptools```). I have then created two new make directives. The first is ```debian-build```, which creates the orig tar and builds it for Debian. The second is ```debian-clean```, which cleans Debian build files. You would start with a fresh repo or run all cleaning directives, make sure all your commits are in, and then run the ```debian-build``` directive.

This should run on something like Debian Bookworm or later and Ubuntu 23.04 or later, as manimpango is now in native repositories. I have most extensively tested on Debian Trixie with XFCE4.

I have not written a Github workflow to send this to releases yet, as I would want to discuss with you how to handle that, such as simply having it be downloaded, creating a repo with something like reprepro, or even trying to get it uploaded to Debian, which would then allow it to be in Ubuntu eventually as well.

Thank you for your hard work on this emoji picker. Let me know if you have any problems and I will try to fix them ASAP. 🖖 (Typed with the package)

### CODE REVIEW

**Comment by 266-750Balloons** [comment]
Also, I just wanted to add I created a separate .desktop file that better matches Debian conventions.

And also, each time, you will have to change the version number in a third place: the Debian changelog.

**Comment by tom-james-watson** [comment]
Hello!

I appreciate the work that has gone into this, but I'm afraid I don't want to add first party support for another packaging format. I think just supporting Snap and Flatpak is enough. It's a lot of added maintenance burden that, in my opinion, is not worth it.

Sorry!

**Comment by 266-750Balloons** [comment]
That's reasonable. Thank you for considering it. As it's something I still personally want, I might just do something unofficial similar to what's done for Arch. If I ever get the time, maybe I'll tidy things up a bit and do a request to package in Debian.

**Comment by tom-james-watson** [comment]
Yeah, nothing stopping you doing that, of course!

**Comment by 266-750Balloons** [comment]
I have a question. Hypothetically, would you merge a pull request to move all logic that changes based on whether the application is running as a Flatpak or a Snap from the program to config.py? For instance, instead of having css.py check config.is_snap and config.is_flatpak, have config do this and expose a variable config.css_path? That way, you could have a separation of paths that change by distribution into config.py and common program logic in the rest of the source.
It's not a necessity, but it might make life easier for me and anyone else who wants to port to another distribution format by allowing us to just patch config.py, a file that doesn't really change that often, to support the distribution format instead of having to make a new patch set for ports every time you change the main program code. This wouldn't really be changing anything for you (no new packaging formats would be added in this patch) and maybe even marginally making your life easier, as you wouldn't have to think about whether it's a Flatpak or a Snap in your main code.

**Comment by tom-james-watson** [comment]
It's a reasonable idea, yeh.

Honestly, my problem is that I am pretty burned out on open source and don't really have the motivation to work on this more at the moment.

**Pull request closed without merging**
