### PR TITLE
Add male-sign and female-sign emojis.

### PR DESCRIPTION
**Pull request by 0x4C4A**
I think they get used enough to warrant inclusion in the emoji set. :)

### CODE REVIEW

**Review by tom-james-watson — CHANGES_REQUESTED** [review]
Hi! Thanks for the PR.

Hmm, this list actually came from https://github.com/muan/emojilib but it doesn't appear to be being updated. Ideally we would have a better way of updating the emoji list without needing to manually add entries, but I guess this is ok for now.

A few things:

You can remove `female` and `male` from the `keywords` - you don't need to repeat words that are already in the emoji's name itself. Search will look at both.

Can you also add `gender` and `sex` to the keywords list for both male and female, please?

Whilst we're at it, it would be good to add the transgender symbol too:

```
  "transgender-symbol":{
    "keywords": ["gender", "sex"],
    "char": "⚧️",
    "fitzpatrick_scale": false,
    "category": "symbols"
  },
```

Thanks!

**Comment by 0x4C4A** [comment]
Thank you, recommended changes have been applied.

**Comment by tom-james-watson** [comment]
Thanks for the contribution! Merging.

**Comment by tom-james-watson** [comment]
Released in 1.1.0

**Pull request merged**
